CREATE TABLE `titles` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`ru` VARCHAR(500) NOT NULL DEFAULT '0',
	`en` VARCHAR(500) NULL DEFAULT '0',
	`cn` VARCHAR(500) NULL DEFAULT '0',
	`fr` VARCHAR(500) NULL DEFAULT '0',
	`es` VARCHAR(500) NULL DEFAULT '0',
	`vn` VARCHAR(500) NULL DEFAULT '0',
	`tr` VARCHAR(500) NULL DEFAULT '0',
	`system` VARCHAR(500) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
